export { default as AstroIco } from "./AstroIco.astro"
export { default as ReactIco } from "./ReactIco.astro"
export { default as NextIco } from "./NextIco.astro"
export { default as TailwindIco } from "./TailwindIco.astro"
export { default as TypeScriptIco } from "./TypeScriptIco.astro"
export { default as JestIco } from "./JestIco.astro"
export { default as ReactNativeIco } from "./ReactNativeIco.astro"