export { default as CircleIco } from "./CircleIco.astro"
export { default as ArrowRightIco } from "./ArrowRightIco.astro"
export { default as MapPinIco } from "./MapPinIco.astro"
export { default as ChevronArrowIco } from "./ChevronArrowIco.astro"
export { default as ExternalLinkIco } from "./ExternalLinkIco.astro"
export { default as ClockIco } from "./ClockIco.astro"
export { default as WorkIco } from "./WorkIco.astro"    
export {default as MonitorCloud} from "./MonitorCloud.astro"